### ISSUE TITLE
Does not seem to work?

### ISSUE THREAD

**Issue by rklec** [matkoch/resharper-fluentvalidation#2]
I have this installed and even the simple live templates `rule` and `validator` don't seem to be there:
![grafik](https://user-images.githubusercontent.com/71322635/131378776-48891e63-3949-4211-9f5d-5c9e0b559d68.png)

## System

Visual Studio 2019
![grafik](https://user-images.githubusercontent.com/71322635/131378609-b3341820-c812-4725-934a-98423feb5e28.png)
JetBrains ReSharper 2021.2 Build 212.0.20210730.153713 built on 2021-07-30
ReSharper 2021.2.20210730.161342

**Comment by matkoch** [comment]
Just pushed `2021.2.1`. Note that the templates only work inside namespaces/types and constructors (rule).

**Comment by rklec** [comment]
Did you also publish that non the marketplace? I did not got any update yet?

**Comment by matkoch** [comment]
@rklec sorry, build failed and I was on vacation in the meantime. Could you check whether it works now?

**Comment by rklec** [comment]
Yes thanks a lot! This works now.
